name: CD

on:
  workflow_dispatch:
  # workflow_dispatch:
  release:
    types: [published]

env:
  TITLE: "Thread-Safe Objects"
  DESCRIPTION: "A combination of generic Thread-Safe objects for .Net development."
  TAGS: "thunderdesign threading thread%2Dsafe thread%2Dsafety threadsafe maui maui%2Dapp c%2Dsharp dotnet%2Dstandard dotnet%2Dframework dotnet%2Dcore cross%2Dplatform pcl%2Dlibrary xamarin unity csharp net dotnet bindable binding"
  #FILE_NAME: ex: "ThunderDesign.Net-PCL.Threading"
  FILE_NAME: "${{ github.event.repository.name }}"
  #REPOSITORY_NAME: ex: "ThunderDesign.Net-PCL.Threading"
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  #REPOSITORY_OWNER: ex: "ThunderDesign"
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  #GITHUB_URL: ex: "https://github.com/ThunderDesign"
  GITHUB_URL: ${{ github.server_url }}/${{ github.repository_owner }}
  #REPOSITORY_URL: ex: "https://github.com/ThunderDesign/ThunderDesign.Net-PCL.Threading"
  REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.repository.name }}
 
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  pack:
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
